### ISSUE TITLE
unordered list are broken when fetched from rich text fragment

### ISSUE THREAD

**Issue by adityaanand07** [prismicio/python-kit#43]
When I have a unordered list in rich text field and is fetched via prismic api then first element of unordered list is broked.
example
suppose we have unordered list as follow

- one
- two
- three

Now when i fetch it using prismic api, it shows as follow in response

```
<li>one</li>
<ul>
    <li>two</li>
   <li>three</li>
</ul>
```

we can see that first element is out of the ul tag

**Comment by srenault** [comment]
Fixed in this PR #44

**Comment by adityaanand07** [comment]
@srenault I tested it and is working fine with the unordered list. Thank You!!
